name: Test and deploy feature branch

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: >
          curl --fail-with-body -X POST -F token=${{ secrets.DEPLOYMENT_TOKEN }}
          -F ref=master -F "variables[SERVICE]=webui2"
          -F "variables[WEBUI2_BRANCH]=${{ github.ref_name }}"
          ${{ secrets.DEPLOYMENT_URL }}
